source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use Postgres as the database for Active Record
gem 'pg'

group :development do
	gem 'pry-debugger'
	gem 'pry-rails'
end

# Use unicorn and nginx as the app server
gem 'unicorn'
gem "nginx"